version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: peyker_db
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: peyker_user
      POSTGRES_PASSWORD: peyker_password
      POSTGRES_DB: peyker_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
